### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Dan-Wood** [regisb/spotify-onthego#10]
Am I missing something here?

```
Traceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 9, in <module>
    load_entry_point('spotify-onthego==0.0.3', 'console_scripts', 'spotify-playlist')()
  File "/usr/local/lib/python2.7/dist-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 35, in audio
    if self.skip_existing and self.should_skip(track):
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 50, in should_skip
    return len(glob(pattern)) != 0
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 39, in iglob
    if os.path.lexists(pathname):
  File "/usr/lib/python2.7/posixpath.py", line 152, in lexists
    os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 35: ordinal not in range(128)

```

**Comment by regisb** [comment]
Hi, thanks for your feedback! No, it's not you, it's probably just python 2 messing around with unicode :) Could you give me the command you tried to execute?

**Comment by Dan-Wood** [comment]
Sure thing! 

` spotify-playlist "Awesomeness" ./music/`

Seems to download some just fine, then hits a snag on certain ones and won't continue. 

For example it was attempting to download F-OO and wouldn't pass F-OO due to the error. It would never past F-OO no matter how many times you re-ran the command. I removed F-OO from the playlist and it continued down the list until it hit the next snag of B-A-R.

```
++ Processing The Police - Every Breath You Take
    Downloading https://www.youtube.com/watch?v=OMOGaugKpzs to /tmp/The Police - Every Breath You Take.webm
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 9, in <module>
    load_entry_point('spotify-onthego==0.0.3', 'console_scripts', 'spotify-playlist')()
  File "/usr/local/lib/python2.7/dist-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 35, in audio
    if self.skip_existing and self.should_skip(track):
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 50, in should_skip
    return len(glob(pattern)) != 0
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 39, in iglob
    if os.path.lexists(pathname):
  File "/usr/lib/python2.7/posixpath.py", line 152, in lexists
    os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 35: ordinal not in range(128)

```

**Comment by regisb** [comment]
This is weird, I can't reproduce. May I ask what is the absolute path to the folder from which you are trying to run the command?

**Comment by Dan-Wood** [comment]
/spot/

I'm now running it in /root/ , I'll let you know if that fixes it.

**Comment by regisb** [comment]
What is the value of the `LANG` environment variable?

    echo $LANG

**Comment by Dan-Wood** [comment]
Nothing.

~# echo $LANG


Good news though .. running it in /root/ has fixed it issue...

**Comment by Dan-Wood** [comment]
I'm jumping the gun in my edits haha.

Same song same issue, I've noticed it downloads 15 and stops, not sure if that's a coincidence or not.

Running in /root/

```
++ Processing The Police - Every Breath You Take
    Downloading https://www.youtube.com/watch?v=OMOGaugKpzs to /tmp/The Police - Every Breath You Take.webm
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 9, in <module>
    load_entry_point('spotify-onthego==0.0.3', 'console_scripts', 'spotify-playlist')()
  File "/usr/local/lib/python2.7/dist-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 35, in audio
    if self.skip_existing and self.should_skip(track):
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 50, in should_skip
    return len(glob(pattern)) != 0
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 39, in iglob
    if os.path.lexists(pathname):
  File "/usr/lib/python2.7/posixpath.py", line 152, in lexists
    os.lstat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 35: ordinal not in range(128)
```

**Comment by Dan-Wood** [comment]
```
~# locale
LANG=
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

```

This has fixed my issue up, sorry for that!

```
locale-gen en_US en_US.UTF-8
dpkg-reconfigure locales 
export LC_ALL="en_US.UTF-8"
```

**Comment by regisb** [comment]
Awesome! You're definitely better off with a propert LANG variable. Anyway, I tried to address your issue in the latest two commits. Feel free to upgrade to 0.0.4.
