### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by Dan-Wood** [regisb/spotify-onthego#11]
+ Processing Kesha - Die Young                                            Traceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 9, in <module>
    load_entry_point('spotify-onthego==0.0.3', 'console_scripts', 'spotify-playlist')()
  File "/usr/local/lib/python2.7/dist-packages/onthego/scripts/cli.py", line 42, in download_playlist                                                     youtube_downloader.audio(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 40, in audio                                                                     audio_file_path = self.download_to_tmp(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 70, in download_to_tmp                                                           video = pafy.new(video_url)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 122, in new                                                                            return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object has no attribute '__getitem__'
root@poke:~# df -h
Filesystem         Size  Used Avail Use% Mounted on
/dev/ploop11048p1  6.8G  1.1G  5.4G  17% /
none               128M  4.0K  128M   1% /dev
none               4.0K     0  4.0K   0% /sys/fs/cgroup
none                26M   60K   26M   1% /run
none               5.0M     0  5.0M   0% /run/lock
none               128M     0  128M   0% /run/shm
none               100M     0  100M   0% /run/user

And another.

++ Processing Rick Astley - Never Gonna Give You Up
Traceback (most recent call last):                                           File "/usr/local/bin/spotify-playlist", line 9, in <module>
    load_entry_point('spotify-onthego==0.0.4', 'console_scripts', 'spotify-playlist')()
  File "/usr/local/lib/python2.7/dist-packages/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 40, in audio
    audio_file_path = self.download_to_tmp(track)
  File "/usr/local/lib/python2.7/dist-packages/onthego/youtube.py", line 70, in download_to_tmp
    video = pafy.new(video_url)
  File "/usr/local/lib/python2.7/dist-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/usr/local/lib/python2.7/dist-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object has no attribute '__getitem__'

Sorry on mobile.

**Comment by regisb** [comment]
This is probably a pafy issue. Did you solve it by just re-running the download script?

**Comment by Dan-Wood** [comment]
Yea seems to go away on re-run. It's quite random doesn't happen all the time.
