### ISSUE TITLE
Crash : _ydl_info is null

### ISSUE THREAD

**Issue by aboutsko** [regisb/spotify-onthego#17]
Got this download-stopper crash. Underlying library fails, maybe it shouldn't stop the playlist download.

++ Processing DubVision - I Found Your Heart - Vocal Radio Edit
Traceback (most recent call last):
  File "/home/sko/Work/spotify-onthego/venv/bin/spotify-playlist", line 11, in <module>
    load_entry_point('spotify-onthego', 'console_scripts', 'spotify-playlist')()
  File "/home/sko/Work/spotify-onthego/onthego/scripts/cli.py", line 42, in download_playlist
    youtube_downloader.audio(track)
  File "/home/sko/Work/spotify-onthego/onthego/youtube.py", line 40, in audio
    audio_file_path = self.download_to_tmp(track)
  File "/home/sko/Work/spotify-onthego/onthego/youtube.py", line 70, in download_to_tmp
    video = pafy.new(video_url)
  File "/home/sko/Work/spotify-onthego/venv/local/lib/python2.7/site-packages/pafy/pafy.py", line 122, in new
    return Pafy(url, basic, gdata, size, callback, ydl_opts)
  File "/home/sko/Work/spotify-onthego/venv/local/lib/python2.7/site-packages/pafy/backend_youtube_dl.py", line 29, in __init__
    super(YtdlPafy, self).__init__(*args, **kwargs)
  File "/home/sko/Work/spotify-onthego/venv/local/lib/python2.7/site-packages/pafy/backend_shared.py", line 95, in __init__
    self._fetch_basic()
  File "/home/sko/Work/spotify-onthego/venv/local/lib/python2.7/site-packages/pafy/backend_youtube_dl.py", line 53, in _fetch_basic
    self._category = self._ydl_info['categories'][0]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by regisb** [comment]
This looks similar to an upstream bug for which I already proposed a patch: https://github.com/mps-youtube/pafy/commit/66d0f262dd230a947015b3f1fa114551d3bc2bc1
Could you please check if the the problem is fixed by upgrading to the head of the pafy module? 

Thanks again for reporting an issue!

**Comment by aboutsko** [comment]
Looks good with it !
Closing.
