### ISSUE TITLE
TypeError: expected string or buffer

### ISSUE THREAD

**Issue by rain0r** [regisb/spotify-onthego#18]
After the command `spotify-playlist "Discover Weekly" ~/`

```Traceback (most recent call last):
  File "/home/rainer/.virtualenvs/spotify-onthego/bin/spotify-playlist", line 11, in <module>
    load_entry_point('spotify-onthego==0.0.5', 'console_scripts', 'spotify-playlist')()
  File "/home/rainer/.virtualenvs/spotify-onthego/lib/python2.7/site-packages/spotify_onthego-0.0.5-py2.7.egg/onthego/scripts/cli.py", line 28, in download_playlist
    elif fnmatch(playlist_name, args.playlist):
  File "/home/rainer/.virtualenvs/spotify-onthego/lib64/python2.7/fnmatch.py", line 43, in fnmatch
    return fnmatchcase(name, pat)
  File "/home/rainer/.virtualenvs/spotify-onthego/lib64/python2.7/fnmatch.py", line 83, in fnmatchcase
    return re_pat.match(name) is not None
TypeError: expected string or buffer
```

**Comment by regisb** [comment]
All of a sudden Spotify started responding to API calls with null playlist names. I will investigate but this is probably an issue with the Spotify API.

**Comment by rain0r** [comment]
This would be a hotfix:

```
    playlist_found = False
    for playlist_id, playlist_name, playlist_owner_id in spotify_client.iter_playlists():
        if playlist_name is None:
            continue

        dst = None
```

**Comment by regisb** [comment]
Your suggested fix would skip many playlists that do have a name, but for which the API response is incomplete.

**Comment by rain0r** [comment]
Yeah I know it's just a hotfix. But I was able to download my Discover Weekly with that.

**Comment by regisb** [comment]
Looks like this issue was fixed upstream by Spotify. Can you confirm? If not, please re-open the issue.
