### ISSUE TITLE
Error with Spotify URI

### ISSUE THREAD

**Issue by rgdagir** [regisb/spotify-onthego#29]
Hi!

I really liked the idea of your tool, but I am having troubles using it...
I set my credentials up, but I can't get the program to run.
Every time I make a call, a random URL open up on my browser. Following the terminal instructions, I copy and paste the URL into the terminal, just to get this error:

```Traceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 11, in <module>
    sys.exit(download_playlist())
  File "/usr/local/lib/python3.6/site-packages/onthego/cli.py", line 28, in download_playlist
    spotify_client = onthego.spotify.Client()
  File "/usr/local/lib/python3.6/site-packages/onthego/spotify.py", line 12, in __init__
    self.spotify = spotipy.Spotify(auth=token_dispenser.spotify_token)
  File "/usr/local/lib/python3.6/site-packages/onthego/auth.py", line 30, in spotify_token
    token = self.get_new_token()
  File "/usr/local/lib/python3.6/site-packages/onthego/auth.py", line 48, in get_new_token
    scope="playlist-read-private user-library-read"
  File "/usr/local/lib/python3.6/site-packages/spotipy/util.py", line 86, in prompt_for_user_token
    token_info = sp_oauth.get_access_token(code)
  File "/usr/local/lib/python3.6/site-packages/spotipy/oauth2.py", line 210, in get_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

Can you help me out, please?
Thanks and congrats on the project!

**Comment by regisb** [comment]
I am afraid I am going to need your spotify client ID and secret to debug this :-/ You should be able to change them after I am done testing. Can you please send them to me by email (github hat behmo dotte com) or irc (regisb@freenode)?

**Comment by JacquesBSTX** [comment]
Hello, I am having the same issue. Is there any way to fix this? Thanks in advance.

**Comment by regisb** [comment]
Is this issue still occurring with the latest 1.0.8 release? If not, please close this issue.
