### ISSUE TITLE
Installationerror

### ISSUE THREAD

**Issue by sonjagabriel** [regisb/spotify-onthego#36]
I tried to install spotify-onthego with $ pip install spotify-onthego and encountered the following error:

Defaulting to user installation because normal site-packages is not writeable
Collecting spotify-onthego
  Using cached spotify-onthego-1.0.10.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vigmex75/spotify-onthego_11f17abab1cf400e94395c1a544999e9/setup.py", line 52, in <module>
          install_requires=get_requirements(),
        File "/tmp/pip-install-vigmex75/spotify-onthego_11f17abab1cf400e94395c1a544999e9/setup.py", line 19, in get_requirements
          for line in open(os.path.join(here, "requirements", "base.in"))
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-vigmex75/spotify-onthego_11f17abab1cf400e94395c1a544999e9/requirements/base.in'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

I am running this on Ubuntu 22.04 and python 3.10.12

**Comment by regisb** [comment]
Thank you for your trust in running this woefully outdated package :sweat_smile: I've published a fix in the latest release. Note that it is very well possible that the package does not anymore, despite that fix...
