### ISSUE TITLE
Timeout Issue while downloading 

### ISSUE THREAD

**Issue by Thomas6013** [regisb/spotify-onthego#37]
Hello everyone,

I have set up everything following the well-done Readme, is this repository still managed ? 

I have a timeout error while I am doing a Spotify download.

Feel free to answer even if these scripts are not maintained anymore. If yes, I can give you more details

Many thanks
Regards

**Comment by regisb** [comment]
Please do give more details including the command you run and the stack trace.

**Comment by Thomas6013** [comment]
Thank you for your quick answer

I don't have any particular logs after I run the command
Just nothing happened even after few hours, this is why I am doing this interruption

```
spotify-playlist "MyPlaylist" ./tmp/hard/
^CTraceback (most recent call last):
  File "/usr/local/bin/spotify-playlist", line 8, in <module>
    sys.exit(download_playlist())
  File "/usr/local/lib/python3.10/dist-packages/onthego/cli.py", line 20, in download_playlist
    spotify_client = onthego.spotify.Client()
  File "/usr/local/lib/python3.10/dist-packages/onthego/spotify.py", line 10, in __init__
    self.spotify = spotipy.Spotify(auth=token_dispenser.spotify_token)
  File "/usr/local/lib/python3.10/dist-packages/onthego/auth.py", line 19, in spotify_token
    token = self.get_new_token()
  File "/usr/local/lib/python3.10/dist-packages/onthego/auth.py", line 25, in get_new_token
    token = spotipy.util.prompt_for_user_token(
  File "/usr/local/lib/python3.10/dist-packages/spotipy/util.py", line 97, in prompt_for_user_token
    code = sp_oauth.get_auth_response()
  File "/usr/local/lib/python3.10/dist-packages/spotipy/oauth2.py", line 480, in get_auth_response
    return self._get_auth_response_local_server(redirect_port)
  File "/usr/local/lib/python3.10/dist-packages/spotipy/oauth2.py", line 449, in _get_auth_response_local_server
    server.handle_request()
  File "/usr/lib/python3.10/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

Hope it can help to understand, I can provide anything else if needed

**Comment by regisb** [comment]
While I try to troubleshoot this issue, can you just tell me how you discovered this repo? It was mostly dormant for about two years, and all of a sudden two different issues were opened here in a week.

**Comment by Thomas6013** [comment]
Many thanks 👍 
I had this specific needs and I found your repository with a reddit thread (I couldn't refind it sorry)
But yeah I saw another issue few days ago so this is why I tried
